let userData: any = {
  id: 1,
  display_name: 'TestUser',
  email: 'test@example.com',
  password_hash: 'hash',
  race: 'ELF',
  class: 'ASSASSIN',
  experience: 100,
  gold: BigInt(1000),
  gold_in_bank: BigInt(5000),
  attack_turns: 10,
  last_active: new Date(),
  units: [],
  items: [],
  bio: 'A test user',
  colorScheme: 'dark',
  locale: 'en-US',
  economy_level: 1,
  fort_level: 1,
  fort_hitpoints: 100,
  house_level: 1,
  totalAttacks: 20,
  totalDefends: 15,
  won_attacks: 10,
  won_defends: 5,
  structure_upgrades: [{ "type": "ARMORY", "level": 0 }, { "type": "SPY", "level": 0 }, { "type": "SENTRY", "level": 0 }, { "type": "OFFENSE", "level": 0 }],
  battle_upgrades: [],
  bonus_points: [],
};

export default userData;