import type { Item } from '@/types/typings';

export const ItemTypes: Item[] = [
  {
    id: 'OFFENSE_DAGGER',
    name: 'Dagger',
    usage: 'OFFENSE',
    level: 1,
    bonus: 25,
    cost: 12500,
    type: 'WEAPON',
    race: 'ALL',
    armoryLevel: 1,
    MeleeAtkPower: 20,
    MeleeDefPower: 5,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'OFFENSE_HATCHET',
    name: 'Hatchet',
    usage: 'OFFENSE',
    level: 2,
    bonus: 50,
    cost: 25000,
    type: 'WEAPON',
    race: 'ALL',
    armoryLevel: 2,
    MeleeAtkPower: 40,
    MeleeDefPower: 10,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'OFFENSE_QUARTERSTAFF',
    name: 'Quarterstaff',
    usage: 'OFFENSE',
    level: 3,
    bonus: 100,
    cost: 50000,
    type: 'WEAPON',
    race: 'ALL',
    armoryLevel: 3,
    MeleeAtkPower: 80,
    MeleeDefPower: 20,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'OFFENSE_MACE',
    name: 'Mace',
    usage: 'OFFENSE',
    level: 4,
    bonus: 225,
    cost: 100000,
    type: 'WEAPON',
    race: 'ALL',
    armoryLevel: 4,
    MeleeAtkPower: 180,
    MeleeDefPower: 45,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'OFFENSE_BATTLE-AXE',
    name: 'Battle Axe',
    usage: 'OFFENSE',
    level: 5,
    bonus: 700,
    cost: 200000,
    type: 'WEAPON',
    race: 'ALL',
    armoryLevel: 5,
    MeleeAtkPower: 560,
    MeleeDefPower: 140,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'OFFENSE_SHORT-SWORD',
    name: 'Short Sword',
    usage: 'OFFENSE',
    level: 6,
    bonus: 1000,
    cost: 500000,
    type: 'WEAPON',
    race: 'ALL',
    armoryLevel: 6,
    MeleeAtkPower: 800,
    MeleeDefPower: 200,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'OFFENSE_LONG-SWORD',
    name: 'Long Sword',
    usage: 'OFFENSE',
    level: 7,
    bonus: 1500,
    cost: 750000,
    type: 'WEAPON',
    race: 'HUMAN',
    armoryLevel: 7,
    MeleeAtkPower: 1200,
    MeleeDefPower: 300,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'OFFENSE_PADDED-HOOD',
    name: 'Padded Hood',
    usage: 'OFFENSE',
    level: 1,
    bonus: 6,
    cost: 3000,
    type: 'HELM',
    race: 'ALL',
    armoryLevel: 1,
    MeleeAtkPower: 1,
    MeleeDefPower: 5,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'OFFENSE_LEATHER-HOOD',
    name: 'Leather Hood',
    usage: 'OFFENSE',
    level: 2,
    bonus: 12,
    cost: 6000,
    type: 'HELM',
    race: 'ALL',
    armoryLevel: 2,
    MeleeAtkPower: 2,
    MeleeDefPower: 10,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'OFFENSE_STUDDED-LEATHER-HOOD',
    name: 'Studded Leather Hood',
    usage: 'OFFENSE',
    level: 3,
    bonus: 25,
    cost: 12500,
    type: 'HELM',
    race: 'ALL',
    armoryLevel: 3,
    MeleeAtkPower: 5,
    MeleeDefPower: 20,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'OFFENSE_PADDED-ARMOR',
    name: 'Padded Armor',
    usage: 'OFFENSE',
    level: 1,
    bonus: 19,
    cost: 9500,
    type: 'ARMOR',
    race: 'ALL',
    armoryLevel: 1,
    MeleeAtkPower: 4,
    MeleeDefPower: 15,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'OFFENSE_LEATHER-ARMOR',
    name: 'Leather Armor',
    usage: 'OFFENSE',
    level: 2,
    bonus: 38,
    cost: 19000,
    type: 'ARMOR',
    race: 'ALL',
    armoryLevel: 2,
    MeleeAtkPower: 8,
    MeleeDefPower: 30,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'OFFENSE_STUDDED-LEATHER-ARMOR',
    name: 'Studded Leather Armor',
    usage: 'OFFENSE',
    level: 3,
    bonus: 75,
    cost: 37500,
    type: 'ARMOR',
    race: 'ALL',
    armoryLevel: 3,
    MeleeAtkPower: 15,
    MeleeDefPower: 60,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'OFFENSE_PADDED-BOOTS',
    name: 'Padded Boots',
    usage: 'OFFENSE',
    level: 1,
    bonus: 6,
    cost: 3000,
    type: 'BOOTS',
    race: 'ALL',
    armoryLevel: 1,
    MeleeAtkPower: 1,
    MeleeDefPower: 5,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'OFFENSE_LEATHER-BOOTS',
    name: 'Leather Boots',
    usage: 'OFFENSE',
    level: 2,
    bonus: 12,
    cost: 6000,
    type: 'BOOTS',
    race: 'ALL',
    armoryLevel: 2,
    MeleeAtkPower: 2,
    MeleeDefPower: 10,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'OFFENSE_STUDDED-LEATHER-BOOTS',
    name: 'Studded Leather Boots',
    usage: 'OFFENSE',
    level: 3,
    bonus: 25,
    cost: 12500,
    type: 'BOOTS',
    race: 'ALL',
    armoryLevel: 3,
    MeleeAtkPower: 5,
    MeleeDefPower: 20,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'OFFENSE_PADDED-BRACERS',
    name: 'Padded Bracers',
    usage: 'OFFENSE',
    level: 1,
    bonus: 3,
    cost: 1500,
    type: 'BRACERS',
    race: 'ALL',
    armoryLevel: 1,
    MeleeAtkPower: 1,
    MeleeDefPower: 2,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'OFFENSE_LEATHER-BRACERS',
    name: 'Leather Bracers',
    usage: 'OFFENSE',
    level: 2,
    bonus: 5,
    cost: 2500,
    type: 'BRACERS',
    race: 'ALL',
    armoryLevel: 2,
    MeleeAtkPower: 2,
    MeleeDefPower: 3,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'OFFENSE_STUDDED-LEATHER-BRACERS',
    name: 'Studded Leather Bracers',
    usage: 'OFFENSE',
    level: 3,
    bonus: 10,
    cost: 5000,
    type: 'BRACERS',
    race: 'ALL',
    armoryLevel: 3,
    MeleeAtkPower: 5,
    MeleeDefPower: 5,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'OFFENSE_SMALL-WOODEN-SHIELD',
    name: 'Small Wooden Shield',
    usage: 'OFFENSE',
    level: 1,
    bonus: 12,
    cost: 6000,
    type: 'SHIELD',
    race: 'ALL',
    armoryLevel: 1,
    MeleeAtkPower: 2,
    MeleeDefPower: 10,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'OFFENSE_MEDIUM-WOODEN-SHIELD',
    name: 'Medium Wooden Shield',
    usage: 'OFFENSE',
    level: 2,
    bonus: 25,
    cost: 12500,
    type: 'SHIELD',
    race: 'ALL',
    armoryLevel: 2,
    MeleeAtkPower: 5,
    MeleeDefPower: 20,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'OFFENSE_LARGE-WOODEN-SHIELD',
    name: 'Large Wooden Shield',
    usage: 'OFFENSE',
    level: 3,
    bonus: 50,
    cost: 25000,
    type: 'SHIELD',
    race: 'ALL',
    armoryLevel: 3,
    MeleeAtkPower: 10,
    MeleeDefPower: 40,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'DEFENSE_SLING',
    name: 'Sling',
    usage: 'DEFENSE',
    level: 1,
    bonus: 25,
    cost: 12500,
    type: 'WEAPON',
    race: 'ALL',
    armoryLevel: 1,
    MeleeAtkPower: 5,
    MeleeDefPower: 5,
    RangedAtkPower: 20, // Ranged attack for DEFENSE item
    RangedDefPower: 10,
  },
  {
    id: 'DEFENSE_HATCHET',
    name: 'Hatchet',
    usage: 'DEFENSE',
    level: 2,
    bonus: 50,
    cost: 25000,
    type: 'WEAPON',
    race: 'ALL',
    armoryLevel: 2,
    MeleeAtkPower: 40,
    MeleeDefPower: 10,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'DEFENSE_SPEAR',
    name: 'Spear',
    usage: 'DEFENSE',
    level: 3,
    bonus: 100,
    cost: 50000,
    type: 'WEAPON',
    race: 'ALL',
    armoryLevel: 3,
    MeleeAtkPower: 80,
    MeleeDefPower: 20,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'DEFENSE_PADDED-HOOD',
    name: 'Padded Hood',
    usage: 'DEFENSE',
    level: 1,
    bonus: 6,
    cost: 3000,
    type: 'HELM',
    race: 'ALL',
    armoryLevel: 1,
    MeleeAtkPower: 1,
    MeleeDefPower: 5,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'DEFENSE_LEATHER-HOOD',
    name: 'Leather Hood',
    usage: 'DEFENSE',
    level: 2,
    bonus: 12,
    cost: 6000,
    type: 'HELM',
    race: 'ALL',
    armoryLevel: 2,
    MeleeAtkPower: 2,
    MeleeDefPower: 10,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'DEFENSE_STUDDED-LEATHER-HOOD',
    name: 'Studded Leather Hood',
    usage: 'DEFENSE',
    level: 3,
    bonus: 25,
    cost: 12500,
    type: 'HELM',
    race: 'ALL',
    armoryLevel: 3,
    MeleeAtkPower: 5,
    MeleeDefPower: 20,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'DEFENSE_PADDED-ARMOR',
    name: 'Padded Armor',
    usage: 'DEFENSE',
    level: 1,
    bonus: 19,
    cost: 9500,
    type: 'ARMOR',
    race: 'ALL',
    armoryLevel: 1,
    MeleeAtkPower: 4,
    MeleeDefPower: 15,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'DEFENSE_LEATHER-ARMOR',
    name: 'Leather Armor',
    usage: 'DEFENSE',
    level: 2,
    bonus: 38,
    cost: 19000,
    type: 'ARMOR',
    race: 'ALL',
    armoryLevel: 2,
    MeleeAtkPower: 8,
    MeleeDefPower: 30,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'DEFENSE_STUDDED-LEATHER-ARMOR',
    name: 'Studded Leather Armor',
    usage: 'DEFENSE',
    level: 3,
    bonus: 75,
    cost: 37500,
    type: 'ARMOR',
    race: 'ALL',
    armoryLevel: 3,
    MeleeAtkPower: 15,
    MeleeDefPower: 60,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'DEFENSE_PADDED-BOOTS',
    name: 'Padded Boots',
    usage: 'DEFENSE',
    level: 1,
    bonus: 6,
    cost: 3000,
    type: 'BOOTS',
    race: 'ALL',
    armoryLevel: 1,
    MeleeAtkPower: 1,
    MeleeDefPower: 5,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'DEFENSE_LEATHER-BOOTS',
    name: 'Leather Boots',
    usage: 'DEFENSE',
    level: 2,
    bonus: 12,
    cost: 6000,
    type: 'BOOTS',
    race: 'ALL',
    armoryLevel: 2,
    MeleeAtkPower: 2,
    MeleeDefPower: 10,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'DEFENSE_STUDDED-LEATHER-BOOTS',
    name: 'Studded Leather Boots',
    usage: 'DEFENSE',
    level: 3,
    bonus: 25,
    cost: 12500,
    type: 'BOOTS',
    race: 'ALL',
    armoryLevel: 3,
    MeleeAtkPower: 5,
    MeleeDefPower: 20,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'DEFENSE_PADDED-BRACERS',
    name: 'Padded Bracers',
    usage: 'DEFENSE',
    level: 1,
    bonus: 3,
    cost: 1500,
    type: 'BRACERS',
    race: 'ALL',
    armoryLevel: 1,
    MeleeAtkPower: 1,
    MeleeDefPower: 2,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'DEFENSE_LEATHER-BRACERS',
    name: 'Leather Bracers',
    usage: 'DEFENSE',
    level: 2,
    bonus: 5,
    cost: 2500,
    type: 'BRACERS',
    race: 'ALL',
    armoryLevel: 2,
    MeleeAtkPower: 2,
    MeleeDefPower: 3,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'DEFENSE_STUDDED-LEATHER-BRACERS',
    name: 'Studded Leather Bracers',
    usage: 'DEFENSE',
    level: 3,
    bonus: 10,
    cost: 5000,
    type: 'BRACERS',
    race: 'ALL',
    armoryLevel: 3,
    MeleeAtkPower: 5,
    MeleeDefPower: 5,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'DEFENSE_SMALL-WOODEN-SHIELD',
    name: 'Small Wooden Shield',
    usage: 'DEFENSE',
    level: 1,
    bonus: 12,
    cost: 6000,
    type: 'SHIELD',
    race: 'ALL',
    armoryLevel: 1,
    MeleeAtkPower: 2,
    MeleeDefPower: 10,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'DEFENSE_MEDIUM-WOODEN-SHIELD',
    name: 'Medium Wooden Shield',
    usage: 'DEFENSE',
    level: 2,
    bonus: 25,
    cost: 12500,
    type: 'SHIELD',
    race: 'ALL',
    armoryLevel: 2,
    MeleeAtkPower: 5,
    MeleeDefPower: 20,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'DEFENSE_LARGE-WOODEN-SHIELD',
    name: 'Large Wooden Shield',
    usage: 'DEFENSE',
    level: 3,
    bonus: 50,
    cost: 25000,
    type: 'SHIELD',
    race: 'ALL',
    armoryLevel: 3,
    MeleeAtkPower: 10,
    MeleeDefPower: 40,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'SPY_SLING',
    name: 'Sling',
    usage: 'SPY',
    level: 1,
    bonus: 25,
    cost: 12500,
    race: 'ALL',
    type: 'WEAPON',
    armoryLevel: 1,
    MeleeAtkPower: 20,
    MeleeDefPower: 5,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'SPY_BRASS-KNUCKLES',
    name: 'Brass Knuckles',
    usage: 'SPY',
    level: 2,
    bonus: 50,
    cost: 25000,
    race: 'ALL',
    type: 'WEAPON',
    armoryLevel: 2,
    MeleeAtkPower: 40,
    MeleeDefPower: 10,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'SPY_CUDGEL',
    name: 'Cudgel',
    usage: 'SPY',
    level: 3,
    bonus: 100,
    cost: 50000,
    race: 'ALL',
    type: 'WEAPON',
    armoryLevel: 3,
    MeleeAtkPower: 80,
    MeleeDefPower: 20,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'SPY_KNIFE',
    name: 'Knife',
    usage: 'SPY',
    level: 4,
    bonus: 225,
    cost: 100000,
    race: 'ALL',
    type: 'WEAPON',
    armoryLevel: 4,
    MeleeAtkPower: 180,
    MeleeDefPower: 45,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'SPY_CLOTH-CAP',
    name: 'Cloth Cap',
    usage: 'SPY',
    level: 1,
    bonus: 6,
    cost: 3000,
    race: 'ALL',
    type: 'HELM',
    armoryLevel: 1,
    MeleeAtkPower: 1,
    MeleeDefPower: 5,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'SPY_PADDED-CAP',
    name: 'Padded Cap',
    usage: 'SPY',
    level: 2,
    bonus: 12,
    cost: 6000,
    race: 'ALL',
    type: 'HELM',
    armoryLevel: 2,
    MeleeAtkPower: 2,
    MeleeDefPower: 10,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'SPY_LEATHER-CAP',
    name: 'Leather Cap',
    usage: 'SPY',
    level: 3,
    bonus: 25,
    cost: 12500,
    race: 'ALL',
    type: 'HELM',
    armoryLevel: 3,
    MeleeAtkPower: 5,
    MeleeDefPower: 20,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'SPY_CLOTH-HOOD',
    name: 'Cloth Hood',
    usage: 'SPY',
    level: 4,
    bonus: 50,
    cost: 25000,
    race: 'ALL',
    type: 'HELM',
    armoryLevel: 4,
    MeleeAtkPower: 10,
    MeleeDefPower: 40,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'SPY_DARK-CLOTH-ARMOR',
    name: 'Dark Cloth Armor',
    usage: 'SPY',
    level: 1,
    bonus: 19,
    cost: 9500,
    race: 'ALL',
    type: 'ARMOR',
    armoryLevel: 1,
    MeleeAtkPower: 4,
    MeleeDefPower: 15,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'SPY_PADDED-CLOTH-ARMOR',
    name: 'Padded Cloth Armor',
    usage: 'SPY',
    level: 2,
    bonus: 38,
    cost: 19000,
    race: 'ALL',
    type: 'ARMOR',
    armoryLevel: 2,
    MeleeAtkPower: 8,
    MeleeDefPower: 30,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'SPY_LEATHER-ARMOR',
    name: 'Leather Armor',
    usage: 'SPY',
    level: 3,
    bonus: 75,
    cost: 37500,
    race: 'ALL',
    type: 'ARMOR',
    armoryLevel: 3,
    MeleeAtkPower: 15,
    MeleeDefPower: 60,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'SPY_PADDED-LEATHER-ARMOR',
    name: 'Padded Leather Armor',
    usage: 'SPY',
    level: 4,
    bonus: 150,
    cost: 75000,
    race: 'ALL',
    type: 'ARMOR',
    armoryLevel: 4,
    MeleeAtkPower: 60,
    MeleeDefPower: 90,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'SPY_CLOTH-BOOTS',
    name: 'Cloth Boots',
    usage: 'SPY',
    level: 1,
    bonus: 6,
    cost: 3000,
    race: 'ALL',
    type: 'BOOTS',
    armoryLevel: 1,
    MeleeAtkPower: 1,
    MeleeDefPower: 5,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'SPY_PADDED-BOOTS',
    name: 'Padded Boots',
    usage: 'SPY',
    level: 2,
    bonus: 12,
    cost: 6000,
    race: 'ALL',
    type: 'BOOTS',
    armoryLevel: 2,
    MeleeAtkPower: 2,
    MeleeDefPower: 10,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'SPY_LEATHER-BOOTS',
    name: 'Leather Boots',
    usage: 'SPY',
    level: 3,
    bonus: 25,
    cost: 12500,
    race: 'ALL',
    type: 'BOOTS',
    armoryLevel: 3,
    MeleeAtkPower: 5,
    MeleeDefPower: 20,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'SPY_PADDED-LEATHER-BOOTS',
    name: 'Padded Leather Boots',
    usage: 'SPY',
    level: 4,
    bonus: 50,
    cost: 25000,
    race: 'ALL',
    type: 'BOOTS',
    armoryLevel: 4,
    MeleeAtkPower: 20,
    MeleeDefPower: 30,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'SPY_CLOTH-BRACERS',
    name: 'Cloth Bracers',
    usage: 'SPY',
    level: 1,
    bonus: 3,
    cost: 1500,
    race: 'ALL',
    type: 'BRACERS',
    armoryLevel: 1,
    MeleeAtkPower: 1,
    MeleeDefPower: 2,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'SPY_PADDED-BRACERS',
    name: 'Padded Bracers',
    usage: 'SPY',
    level: 2,
    bonus: 5,
    cost: 2500,
    race: 'ALL',
    type: 'BRACERS',
    armoryLevel: 2,
    MeleeAtkPower: 2,
    MeleeDefPower: 3,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'SPY_LEATHER-BRACERS',
    name: 'Leather Bracers',
    usage: 'SPY',
    level: 3,
    bonus: 10,
    cost: 5000,
    race: 'ALL',
    type: 'BRACERS',
    armoryLevel: 3,
    MeleeAtkPower: 5,
    MeleeDefPower: 5,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'SPY_PADDED-LEATHER-BRACERS',
    name: 'Padded Leather Bracers',
    usage: 'SPY',
    level: 4,
    bonus: 20,
    cost: 10000,
    race: 'ALL',
    type: 'BRACERS',
    armoryLevel: 4,
    MeleeAtkPower: 8,
    MeleeDefPower: 12,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'SENTRY_SLING',
    name: 'Sling',
    usage: 'SENTRY',
    level: 1,
    bonus: 25,
    cost: 12500,
    race: 'ALL',
    type: 'WEAPON',
    armoryLevel: 1,
    MeleeAtkPower: 20,
    MeleeDefPower: 5,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'SENTRY_DAGGER',
    name: 'Dagger',
    usage: 'SENTRY',
    level: 2,
    bonus: 50,
    cost: 25000,
    race: 'ALL',
    type: 'WEAPON',
    armoryLevel: 2,
    MeleeAtkPower: 40,
    MeleeDefPower: 10,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'SENTRY_HATCHET',
    name: 'Hatchet',
    usage: 'SENTRY',
    level: 3,
    bonus: 100,
    cost: 50000,
    race: 'ALL',
    type: 'WEAPON',
    armoryLevel: 3,
    MeleeAtkPower: 80,
    MeleeDefPower: 20,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'SENTRY_QUARTERSTAFF',
    name: 'Quarterstaff',
    usage: 'SENTRY',
    level: 4,
    bonus: 225,
    cost: 100000,
    race: 'ALL',
    type: 'WEAPON',
    armoryLevel: 4,
    MeleeAtkPower: 180,
    MeleeDefPower: 45,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'SENTRY_MACE',
    name: 'Mace',
    usage: 'SENTRY',
    level: 5,
    bonus: 700,
    cost: 200000,
    race: 'ALL',
    type: 'WEAPON',
    armoryLevel: 5,
    MeleeAtkPower: 560,
    MeleeDefPower: 140,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'SENTRY_PADDED-HOOD',
    name: 'Padded Hood',
    usage: 'SENTRY',
    level: 1,
    bonus: 6,
    cost: 3000,
    race: 'ALL',
    type: 'HELM',
    armoryLevel: 1,
    MeleeAtkPower: 1,
    MeleeDefPower: 5,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'SENTRY_LEATHER-HOOD',
    name: 'Leather Hood',
    usage: 'SENTRY',
    level: 2,
    bonus: 12,
    cost: 6000,
    race: 'ALL',
    type: 'HELM',
    armoryLevel: 2,
    MeleeAtkPower: 2,
    MeleeDefPower: 10,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'SENTRY_STUDDED-LEATHER-HOOD',
    name: 'Studded Leather Hood',
    usage: 'SENTRY',
    level: 3,
    bonus: 25,
    cost: 12500,
    race: 'ALL',
    type: 'HELM',
    armoryLevel: 3,
    MeleeAtkPower: 5,
    MeleeDefPower: 20,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'SENTRY_BRONZE-CAP',
    name: 'Bronze Cap',
    usage: 'SENTRY',
    level: 4,
    bonus: 50,
    cost: 25000,
    race: 'ALL',
    type: 'HELM',
    armoryLevel: 4,
    MeleeAtkPower: 10,
    MeleeDefPower: 40,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'SENTRY_PADDED-ARMOR',
    name: 'Padded Armor',
    usage: 'SENTRY',
    level: 1,
    bonus: 19,
    cost: 9500,
    race: 'ALL',
    type: 'ARMOR',
    armoryLevel: 1,
    MeleeAtkPower: 4,
    MeleeDefPower: 15,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'SENTRY_LEATHER-ARMOR',
    name: 'Leather Armor',
    usage: 'SENTRY',
    level: 2,
    bonus: 38,
    cost: 19000,
    race: 'ALL',
    type: 'ARMOR',
    armoryLevel: 2,
    MeleeAtkPower: 8,
    MeleeDefPower: 30,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'SENTRY_STUDDED-LEATHER-ARMOR',
    name: 'Studded Leather Armor',
    usage: 'SENTRY',
    level: 3,
    bonus: 75,
    cost: 37500,
    race: 'ALL',
    type: 'ARMOR',
    armoryLevel: 3,
    MeleeAtkPower: 15,
    MeleeDefPower: 60,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'SENTRY_BRONZE-CHAINMAIL',
    name: 'Bronze Chainmail',
    usage: 'SENTRY',
    level: 4,
    bonus: 150,
    cost: 75000,
    race: 'ALL',
    type: 'ARMOR',
    armoryLevel: 4,
    MeleeAtkPower: 60,
    MeleeDefPower: 90,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'SENTRY_PADDED-BOOTS',
    name: 'Padded Boots',
    usage: 'SENTRY',
    level: 1,
    bonus: 6,
    cost: 3000,
    race: 'ALL',
    type: 'BOOTS',
    armoryLevel: 1,
    MeleeAtkPower: 1,
    MeleeDefPower: 5,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'SENTRY_LEATHER-BOOTS',
    name: 'Leather Boots',
    usage: 'SENTRY',
    level: 2,
    bonus: 12,
    cost: 6000,
    race: 'ALL',
    type: 'BOOTS',
    armoryLevel: 2,
    MeleeAtkPower: 2,
    MeleeDefPower: 10,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'SENTRY_STUDDED-LEATHER-GREAVES',
    name: 'Studded Leather Greaves',
    usage: 'SENTRY',
    level: 3,
    bonus: 25,
    cost: 12500,
    race: 'ALL',
    type: 'BOOTS',
    armoryLevel: 3,
    MeleeAtkPower: 5,
    MeleeDefPower: 20,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'SENTRY_BRONZE-CHAIN-GREAVES',
    name: 'Bronze Chain Greaves',
    usage: 'SENTRY',
    level: 4,
    bonus: 50,
    cost: 25000,
    race: 'ALL',
    type: 'BOOTS',
    armoryLevel: 4,
    MeleeAtkPower: 20,
    MeleeDefPower: 30,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'SENTRY_PADDED-BRACERS',
    name: 'Padded Bracers',
    usage: 'SENTRY',
    level: 1,
    bonus: 3,
    cost: 1500,
    race: 'ALL',
    type: 'BRACERS',
    armoryLevel: 1,
    MeleeAtkPower: 1,
    MeleeDefPower: 2,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'SENTRY_LEATHER-BRACERS',
    name: 'Leather Bracers',
    usage: 'SENTRY',
    level: 2,
    bonus: 5,
    cost: 2500,
    race: 'ALL',
    type: 'BRACERS',
    armoryLevel: 2,
    MeleeAtkPower: 2,
    MeleeDefPower: 3,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'SENTRY_STUDDED-LEATHER-BRACERS',
    name: 'Studded Leather Bracers',
    usage: 'SENTRY',
    level: 3,
    bonus: 10,
    cost: 5000,
    race: 'ALL',
    type: 'BRACERS',
    armoryLevel: 3,
    MeleeAtkPower: 5,
    MeleeDefPower: 5,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'SENTRY_BRONZE-CHAIN-BRACERS',
    name: 'Bronze Chain Bracers',
    usage: 'SENTRY',
    level: 4,
    bonus: 20,
    cost: 10000,
    race: 'ALL',
    type: 'BRACERS',
    armoryLevel: 4,
    MeleeAtkPower: 8,
    MeleeDefPower: 12,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'SENTRY_SMALL-WOODEN-SHIELD',
    name: 'Small Wooden Shield',
    usage: 'SENTRY',
    level: 1,
    bonus: 12,
    cost: 6000,
    race: 'ALL',
    type: 'SHIELD',
    armoryLevel: 1,
    MeleeAtkPower: 2,
    MeleeDefPower: 10,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'SENTRY_MEDIUM-WOODEN-SHIELD',
    name: 'Medium Wooden Shield',
    usage: 'SENTRY',
    level: 2,
    bonus: 25,
    cost: 12500,
    race: 'ALL',
    type: 'SHIELD',
    armoryLevel: 2,
    MeleeAtkPower: 5,
    MeleeDefPower: 20,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'SENTRY_LARGE-WOODEN-SHIELD',
    name: 'Large Wooden Shield',
    usage: 'SENTRY',
    level: 3,
    bonus: 50,
    cost: 25000,
    race: 'ALL',
    type: 'SHIELD',
    armoryLevel: 3,
    MeleeAtkPower: 10,
    MeleeDefPower: 40,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'SENTRY_BRONZE-STUDDED-SHIELD',
    name: 'Bronze Studded Shield',
    usage: 'SENTRY',
    level: 4,
    bonus: 100,
    cost: 50000,
    race: 'ALL',
    type: 'SHIELD',
    armoryLevel: 4,
    MeleeAtkPower: 40,
    MeleeDefPower: 60,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'OFFENSE_GREAT-SWORD',
    name: 'Great Sword',
    usage: 'OFFENSE',
    level: 6,
    bonus: 1200,
    cost: 600000,
    type: 'WEAPON',
    race: 'HUMAN',
    armoryLevel: 5,
    MeleeAtkPower: 960,
    MeleeDefPower: 240,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    id: 'OFFENSE_ELVEN-LONGBOW',
    name: 'Elven Longbow',
    usage: 'OFFENSE',
    level: 6,
    bonus: 1200,
    cost: 600000,
    type: 'WEAPON',
    race: 'ELF',
    armoryLevel: 5,
    MeleeAtkPower: 960,
    MeleeDefPower: 240,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  }
];
