import type { Item } from '@/types/typings';

export const ItemTypes: Item[] = [
  {
    name: 'Dagger',
    usage: 'OFFENSE',
    level: 1,
    bonus: 25,
    cost: 12500,
    type: 'WEAPON',
    race: 'ALL',
    armoryLevel: 1,
    quantity: 0,
    killingStrength: 20,
    defenseStrength: 5
  },
  {
    name: 'Hatchet',
    usage: 'OFFENSE',
    level: 2,
    bonus: 50,
    cost: 25000,
    type: 'WEAPON',
    race: 'ALL',
    armoryLevel: 2,
    quantity: 0,
    killingStrength: 40,
    defenseStrength: 10
  },
  {
    name: 'Quarterstaff',
    usage: 'OFFENSE',
    level: 3,
    bonus: 100,
    cost: 50000,
    type: 'WEAPON',
    race: 'ALL',
    armoryLevel: 3,
    quantity: 0,
    killingStrength: 80,
    defenseStrength: 20
  },
  {
    name: 'Mace',
    usage: 'OFFENSE',
    level: 4,
    bonus: 225,
    cost: 100000,
    type: 'WEAPON',
    race: 'ALL',
    armoryLevel: 4,
    quantity: 0,
    killingStrength: 180,
    defenseStrength: 45
  },
  {
    name: 'Battle Axe',
    usage: 'OFFENSE',
    level: 5,
    bonus: 700,
    cost: 200000,
    type: 'WEAPON',
    race: 'ALL',
    armoryLevel: 5,
    quantity: 0,
    killingStrength: 560,
    defenseStrength: 140
  },
  {
    name: 'Short Sword',
    usage: 'OFFENSE',
    level: 6,
    bonus: 1000,
    cost: 500000,
    type: 'WEAPON',
    race: 'ALL',
    armoryLevel: 6,
    quantity: 0,
    killingStrength: 800,
    defenseStrength: 200
  },
  {
    name: 'Long Sword',
    usage: 'OFFENSE',
    level: 7,
    bonus: 1500,
    cost: 750000,
    type: 'WEAPON',
    race: 'HUMAN',
    armoryLevel: 7,
    quantity: 0,
    killingStrength: 1200,
    defenseStrength: 300
  },
  {
    name: 'Padded Hood',
    usage: 'OFFENSE',
    level: 1,
    bonus: 6,
    cost: 3000,
    type: 'HELM',
    race: 'ALL',
    armoryLevel: 1,
    quantity: 0,
    killingStrength: 1,
    defenseStrength: 5
  },
  {
    name: 'Leather Hood',
    usage: 'OFFENSE',
    level: 2,
    bonus: 12,
    cost: 6000,
    type: 'HELM',
    race: 'ALL',
    armoryLevel: 2,
    quantity: 0,
    killingStrength: 2,
    defenseStrength: 10
  },
  {
    name: 'Studded Leather Hood',
    usage: 'OFFENSE',
    level: 3,
    bonus: 25,
    cost: 12500,
    type: 'HELM',
    race: 'ALL',
    armoryLevel: 3,
    quantity: 0,
    killingStrength: 5,
    defenseStrength: 20
  },
  {
    name: 'Padded Armor',
    usage: 'OFFENSE',
    level: 1,
    bonus: 19,
    cost: 9500,
    type: 'ARMOR',
    race: 'ALL',
    armoryLevel: 1,
    quantity: 0,
    killingStrength: 4,
    defenseStrength: 15
  },
  {
    name: 'Leather Armor',
    usage: 'OFFENSE',
    level: 2,
    bonus: 38,
    cost: 19000,
    type: 'ARMOR',
    race: 'ALL',
    armoryLevel: 2,
    quantity: 0,
    killingStrength: 8,
    defenseStrength: 30
  },
  {
    name: 'Studded Leather Armor',
    usage: 'OFFENSE',
    level: 3,
    bonus: 75,
    cost: 37500,
    type: 'ARMOR',
    race: 'ALL',
    armoryLevel: 3,
    quantity: 0,
    killingStrength: 15,
    defenseStrength: 60
  },
  {
    name: 'Padded Boots',
    usage: 'OFFENSE',
    level: 1,
    bonus: 6,
    cost: 3000,
    type: 'BOOTS',
    race: 'ALL',
    armoryLevel: 1,
    quantity: 0,
    killingStrength: 1,
    defenseStrength: 5
  },
  {
    name: 'Leather Boots',
    usage: 'OFFENSE',
    level: 2,
    bonus: 12,
    cost: 6000,
    type: 'BOOTS',
    race: 'ALL',
    armoryLevel: 2,
    quantity: 0,
    killingStrength: 2,
    defenseStrength: 10
  },
  {
    name: 'Studded Leather Boots',
    usage: 'OFFENSE',
    level: 3,
    bonus: 25,
    cost: 12500,
    type: 'BOOTS',
    race: 'ALL',
    armoryLevel: 3,
    quantity: 0,
    killingStrength: 5,
    defenseStrength: 20
  },
  {
    name: 'Padded Bracers',
    usage: 'OFFENSE',
    level: 1,
    bonus: 3,
    cost: 1500,
    type: 'BRACERS',
    race: 'ALL',
    armoryLevel: 1,
    quantity: 0,
    killingStrength: 1,
    defenseStrength: 2
  },
  {
    name: 'Leather Bracers',
    usage: 'OFFENSE',
    level: 2,
    bonus: 5,
    cost: 2500,
    type: 'BRACERS',
    race: 'ALL',
    armoryLevel: 2,
    quantity: 0,
    killingStrength: 2,
    defenseStrength: 3
  },
  {
    name: 'Studded Leather Bracers',
    usage: 'OFFENSE',
    level: 3,
    bonus: 10,
    cost: 5000,
    type: 'BRACERS',
    race: 'ALL',
    armoryLevel: 3,
    quantity: 0,
    killingStrength: 5,
    defenseStrength: 5
  },
  {
    name: 'Small Wooden Shield',
    usage: 'OFFENSE',
    level: 1,
    bonus: 12,
    cost: 6000,
    type: 'SHIELD',
    race: 'ALL',
    armoryLevel: 1,
    quantity: 0,
    killingStrength: 2,
    defenseStrength: 10
  },
  {
    name: 'Medium Wooden Shield',
    usage: 'OFFENSE',
    level: 2,
    bonus: 25,
    cost: 12500,
    type: 'SHIELD',
    race: 'ALL',
    armoryLevel: 2,
    quantity: 0,
    killingStrength: 5,
    defenseStrength: 20
  },
  {
    name: 'Large Wooden Shield',
    usage: 'OFFENSE',
    level: 3,
    bonus: 50,
    cost: 25000,
    type: 'SHIELD',
    race: 'ALL',
    armoryLevel: 3,
    quantity: 0,
    killingStrength: 10,
    defenseStrength: 40
  },
  {
    name: 'Sling',
    usage: 'DEFENSE',
    level: 1,
    bonus: 25,
    cost: 12500,
    type: 'WEAPON',
    race: 'ALL',
    armoryLevel: 1,
    quantity: 0,
    killingStrength: 20,
    defenseStrength: 5
  },
  {
    name: 'Hatchet',
    usage: 'DEFENSE',
    level: 2,
    bonus: 50,
    cost: 25000,
    type: 'WEAPON',
    race: 'ALL',
    armoryLevel: 2,
    quantity: 0,
    killingStrength: 40,
    defenseStrength: 10
  },
  {
    name: 'Spear',
    usage: 'DEFENSE',
    level: 3,
    bonus: 100,
    cost: 50000,
    type: 'WEAPON',
    race: 'ALL',
    armoryLevel: 3,
    quantity: 0,
    killingStrength: 80,
    defenseStrength: 20
  },
  {
    name: 'Padded Hood',
    usage: 'DEFENSE',
    level: 1,
    bonus: 6,
    cost: 3000,
    type: 'HELM',
    race: 'ALL',
    armoryLevel: 1,
    quantity: 0,
    killingStrength: 1,
    defenseStrength: 5
  },
  {
    name: 'Leather Hood',
    usage: 'DEFENSE',
    level: 2,
    bonus: 12,
    cost: 6000,
    type: 'HELM',
    race: 'ALL',
    armoryLevel: 2,
    quantity: 0,
    killingStrength: 2,
    defenseStrength: 10
  },
  {
    name: 'Studded Leather Hood',
    usage: 'DEFENSE',
    level: 3,
    bonus: 25,
    cost: 12500,
    type: 'HELM',
    race: 'ALL',
    armoryLevel: 3,
    quantity: 0,
    killingStrength: 5,
    defenseStrength: 20
  },
  {
    name: 'Padded Armor',
    usage: 'DEFENSE',
    level: 1,
    bonus: 19,
    cost: 9500,
    type: 'ARMOR',
    race: 'ALL',
    armoryLevel: 1,
    quantity: 0,
    killingStrength: 4,
    defenseStrength: 15
  },
  {
    name: 'Leather Armor',
    usage: 'DEFENSE',
    level: 2,
    bonus: 38,
    cost: 19000,
    type: 'ARMOR',
    race: 'ALL',
    armoryLevel: 2,
    quantity: 0,
    killingStrength: 8,
    defenseStrength: 30
  },
  {
    name: 'Studded Leather Armor',
    usage: 'DEFENSE',
    level: 3,
    bonus: 75,
    cost: 37500,
    type: 'ARMOR',
    race: 'ALL',
    armoryLevel: 3,
    quantity: 0,
    killingStrength: 15,
    defenseStrength: 60
  },
  {
    name: 'Padded Boots',
    usage: 'DEFENSE',
    level: 1,
    bonus: 6,
    cost: 3000,
    type: 'BOOTS',
    race: 'ALL',
    armoryLevel: 1,
    quantity: 0,
    killingStrength: 1,
    defenseStrength: 5
  },
  {
    name: 'Leather Boots',
    usage: 'DEFENSE',
    level: 2,
    bonus: 12,
    cost: 6000,
    type: 'BOOTS',
    race: 'ALL',
    armoryLevel: 2,
    quantity: 0,
    killingStrength: 2,
    defenseStrength: 10
  },
  {
    name: 'Studded Leather Boots',
    usage: 'DEFENSE',
    level: 3,
    bonus: 25,
    cost: 12500,
    type: 'BOOTS',
    race: 'ALL',
    armoryLevel: 3,
    quantity: 0,
    killingStrength: 5,
    defenseStrength: 20
  },
  {
    name: 'Padded Bracers',
    usage: 'DEFENSE',
    level: 1,
    bonus: 3,
    cost: 1500,
    type: 'BRACERS',
    race: 'ALL',
    armoryLevel: 1,
    quantity: 0,
    killingStrength: 1,
    defenseStrength: 2
  },
  {
    name: 'Leather Bracers',
    usage: 'DEFENSE',
    level: 2,
    bonus: 5,
    cost: 2500,
    type: 'BRACERS',
    race: 'ALL',
    armoryLevel: 2,
    quantity: 0,
    killingStrength: 2,
    defenseStrength: 3
  },
  {
    name: 'Studded Leather Bracers',
    usage: 'DEFENSE',
    level: 3,
    bonus: 10,
    cost: 5000,
    type: 'BRACERS',
    race: 'ALL',
    armoryLevel: 3,
    quantity: 0,
    killingStrength: 5,
    defenseStrength: 5
  },
  {
    name: 'Small Wooden Shield',
    usage: 'DEFENSE',
    level: 1,
    bonus: 12,
    cost: 6000,
    type: 'SHIELD',
    race: 'ALL',
    armoryLevel: 1,
    quantity: 0,
    killingStrength: 2,
    defenseStrength: 10
  },
  {
    name: 'Medium Wooden Shield',
    usage: 'DEFENSE',
    level: 2,
    bonus: 25,
    cost: 12500,
    type: 'SHIELD',
    race: 'ALL',
    armoryLevel: 2,
    quantity: 0,
    killingStrength: 5,
    defenseStrength: 20
  },
  {
    name: 'Large Wooden Shield',
    usage: 'DEFENSE',
    level: 3,
    bonus: 50,
    cost: 25000,
    type: 'SHIELD',
    race: 'ALL',
    armoryLevel: 3,
    quantity: 0,
    killingStrength: 10,
    defenseStrength: 40
  },
  {
    name: 'Sling',
    usage: 'SPY',
    level: 1,
    bonus: 25,
    cost: 12500,
    race: 'ALL',
    type: 'WEAPON',
    armoryLevel: 1,
    quantity: 0,
    killingStrength: 20,
    defenseStrength: 5
  },
  {
    name: 'Brass Knuckles',
    usage: 'SPY',
    level: 2,
    bonus: 50,
    cost: 25000,
    race: 'ALL',
    type: 'WEAPON',
    armoryLevel: 2,
    quantity: 0,
    killingStrength: 40,
    defenseStrength: 10
  },
  {
    name: 'Cudgel',
    usage: 'SPY',
    level: 3,
    bonus: 100,
    cost: 50000,
    race: 'ALL',
    type: 'WEAPON',
    armoryLevel: 3,
    quantity: 0,
    killingStrength: 80,
    defenseStrength: 20
  },
  {
    name: 'Knife',
    usage: 'SPY',
    level: 4,
    bonus: 225,
    cost: 100000,
    race: 'ALL',
    type: 'WEAPON',
    armoryLevel: 4,
    quantity: 0,
    killingStrength: 180,
    defenseStrength: 45
  },
  {
    name: 'Cloth Cap',
    usage: 'SPY',
    level: 1,
    bonus: 6,
    cost: 3000,
    race: 'ALL',
    type: 'HELM',
    armoryLevel: 1,
    quantity: 0,
    killingStrength: 1,
    defenseStrength: 5
  },
  {
    name: 'Padded Cap',
    usage: 'SPY',
    level: 2,
    bonus: 12,
    cost: 6000,
    race: 'ALL',
    type: 'HELM',
    armoryLevel: 2,
    quantity: 0,
    killingStrength: 2,
    defenseStrength: 10
  },
  {
    name: 'Leather Cap',
    usage: 'SPY',
    level: 3,
    bonus: 25,
    cost: 12500,
    race: 'ALL',
    type: 'HELM',
    armoryLevel: 3,
    quantity: 0,
    killingStrength: 5,
    defenseStrength: 20
  },
  {
    name: 'Cloth Hood',
    usage: 'SPY',
    level: 4,
    bonus: 50,
    cost: 25000,
    race: 'ALL',
    type: 'HELM',
    armoryLevel: 4,
    quantity: 0,
    killingStrength: 10,
    defenseStrength: 40
  },
  {
    name: 'Dark Cloth Armor',
    usage: 'SPY',
    level: 1,
    bonus: 19,
    cost: 9500,
    race: 'ALL',
    type: 'ARMOR',
    armoryLevel: 1,
    quantity: 0,
    killingStrength: 4,
    defenseStrength: 15
  },
  {
    name: 'Padded Cloth Armor',
    usage: 'SPY',
    level: 2,
    bonus: 38,
    cost: 19000,
    race: 'ALL',
    type: 'ARMOR',
    armoryLevel: 2,
    quantity: 0,
    killingStrength: 8,
    defenseStrength: 30
  },
  {
    name: 'Leather Armor',
    usage: 'SPY',
    level: 3,
    bonus: 75,
    cost: 37500,
    race: 'ALL',
    type: 'ARMOR',
    armoryLevel: 3,
    quantity: 0,
    killingStrength: 15,
    defenseStrength: 60
  },
  {
    name: 'Padded Leather Armor',
    usage: 'SPY',
    level: 4,
    bonus: 150,
    cost: 75000,
    race: 'ALL',
    type: 'ARMOR',
    armoryLevel: 4,
    quantity: 0,
    killingStrength: 60,
    defenseStrength: 90
  },
  {
    name: 'Cloth Boots',
    usage: 'SPY',
    level: 1,
    bonus: 6,
    cost: 3000,
    race: 'ALL',
    type: 'BOOTS',
    armoryLevel: 1,
    quantity: 0,
    killingStrength: 1,
    defenseStrength: 5
  },
  {
    name: 'Padded Boots',
    usage: 'SPY',
    level: 2,
    bonus: 12,
    cost: 6000,
    race: 'ALL',
    type: 'BOOTS',
    armoryLevel: 2,
    quantity: 0,
    killingStrength: 2,
    defenseStrength: 10
  },
  {
    name: 'Leather Boots',
    usage: 'SPY',
    level: 3,
    bonus: 25,
    cost: 12500,
    race: 'ALL',
    type: 'BOOTS',
    armoryLevel: 3,
    quantity: 0,
    killingStrength: 5,
    defenseStrength: 20
  },
  {
    name: 'Padded Leather Boots',
    usage: 'SPY',
    level: 4,
    bonus: 50,
    cost: 25000,
    race: 'ALL',
    type: 'BOOTS',
    armoryLevel: 4,
    quantity: 0,
    killingStrength: 20,
    defenseStrength: 30
  },
  {
    name: 'Cloth Bracers',
    usage: 'SPY',
    level: 1,
    bonus: 3,
    cost: 1500,
    race: 'ALL',
    type: 'BRACERS',
    armoryLevel: 1,
    quantity: 0,
    killingStrength: 1,
    defenseStrength: 2
  },
  {
    name: 'Padded Bracers',
    usage: 'SPY',
    level: 2,
    bonus: 5,
    cost: 2500,
    race: 'ALL',
    type: 'BRACERS',
    armoryLevel: 2,
    quantity: 0,
    killingStrength: 2,
    defenseStrength: 3
  },
  {
    name: 'Leather Bracers',
    usage: 'SPY',
    level: 3,
    bonus: 10,
    cost: 5000,
    race: 'ALL',
    type: 'BRACERS',
    armoryLevel: 3,
    quantity: 0,
    killingStrength: 5,
    defenseStrength: 5
  },
  {
    name: 'Padded Leather Bracers',
    usage: 'SPY',
    level: 4,
    bonus: 20,
    cost: 10000,
    race: 'ALL',
    type: 'BRACERS',
    armoryLevel: 4,
    quantity: 0,
    killingStrength: 8,
    defenseStrength: 12
  },
  {
    name: 'Sling',
    usage: 'SENTRY',
    level: 1,
    bonus: 25,
    cost: 12500,
    race: 'ALL',
    type: 'WEAPON',
    armoryLevel: 1,
    quantity: 0,
    killingStrength: 20,
    defenseStrength: 5
  },
  {
    name: 'Dagger',
    usage: 'SENTRY',
    level: 2,
    bonus: 50,
    cost: 25000,
    race: 'ALL',
    type: 'WEAPON',
    armoryLevel: 2,
    quantity: 0,
    killingStrength: 40,
    defenseStrength: 10
  },
  {
    name: 'Hatchet',
    usage: 'SENTRY',
    level: 3,
    bonus: 100,
    cost: 50000,
    race: 'ALL',
    type: 'WEAPON',
    armoryLevel: 3,
    quantity: 0,
    killingStrength: 80,
    defenseStrength: 20
  },
  {
    name: 'Quarterstaff',
    usage: 'SENTRY',
    level: 4,
    bonus: 225,
    cost: 100000,
    race: 'ALL',
    type: 'WEAPON',
    armoryLevel: 4,
    quantity: 0,
    killingStrength: 180,
    defenseStrength: 45
  },
  {
    name: 'Mace',
    usage: 'SENTRY',
    level: 5,
    bonus: 700,
    cost: 200000,
    race: 'ALL',
    type: 'WEAPON',
    armoryLevel: 5,
    quantity: 0,
    killingStrength: 560,
    defenseStrength: 140
  },
  {
    name: 'Padded Hood',
    usage: 'SENTRY',
    level: 1,
    bonus: 6,
    cost: 3000,
    race: 'ALL',
    type: 'HELM',
    armoryLevel: 1,
    quantity: 0,
    killingStrength: 1,
    defenseStrength: 5
  },
  {
    name: 'Leather Hood',
    usage: 'SENTRY',
    level: 2,
    bonus: 12,
    cost: 6000,
    race: 'ALL',
    type: 'HELM',
    armoryLevel: 2,
    quantity: 0,
    killingStrength: 2,
    defenseStrength: 10
  },
  {
    name: 'Studded Leather Hood',
    usage: 'SENTRY',
    level: 3,
    bonus: 25,
    cost: 12500,
    race: 'ALL',
    type: 'HELM',
    armoryLevel: 3,
    quantity: 0,
    killingStrength: 5,
    defenseStrength: 20
  },
  {
    name: 'Bronze Cap',
    usage: 'SENTRY',
    level: 4,
    bonus: 50,
    cost: 25000,
    race: 'ALL',
    type: 'HELM',
    armoryLevel: 4,
    quantity: 0,
    killingStrength: 10,
    defenseStrength: 40
  },
  {
    name: 'Padded Armor',
    usage: 'SENTRY',
    level: 1,
    bonus: 19,
    cost: 9500,
    race: 'ALL',
    type: 'ARMOR',
    armoryLevel: 1,
    quantity: 0,
    killingStrength: 4,
    defenseStrength: 15
  },
  {
    name: 'Leather Armor',
    usage: 'SENTRY',
    level: 2,
    bonus: 38,
    cost: 19000,
    race: 'ALL',
    type: 'ARMOR',
    armoryLevel: 2,
    quantity: 0,
    killingStrength: 8,
    defenseStrength: 30
  },
  {
    name: 'Studded Leather Armor',
    usage: 'SENTRY',
    level: 3,
    bonus: 75,
    cost: 37500,
    race: 'ALL',
    type: 'ARMOR',
    armoryLevel: 3,
    quantity: 0,
    killingStrength: 15,
    defenseStrength: 60
  },
  {
    name: 'Bronze Chainmail',
    usage: 'SENTRY',
    level: 4,
    bonus: 150,
    cost: 75000,
    race: 'ALL',
    type: 'ARMOR',
    armoryLevel: 4,
    quantity: 0,
    killingStrength: 60,
    defenseStrength: 90
  },
  {
    name: 'Padded Boots',
    usage: 'SENTRY',
    level: 1,
    bonus: 6,
    cost: 3000,
    race: 'ALL',
    type: 'BOOTS',
    armoryLevel: 1,
    quantity: 0,
    killingStrength: 1,
    defenseStrength: 5
  },
  {
    name: 'Leather Boots',
    usage: 'SENTRY',
    level: 2,
    bonus: 12,
    cost: 6000,
    race: 'ALL',
    type: 'BOOTS',
    armoryLevel: 2,
    quantity: 0,
    killingStrength: 2,
    defenseStrength: 10
  },
  {
    name: 'Studded Leather Greaves',
    usage: 'SENTRY',
    level: 3,
    bonus: 25,
    cost: 12500,
    race: 'ALL',
    type: 'BOOTS',
    armoryLevel: 3,
    quantity: 0,
    killingStrength: 5,
    defenseStrength: 20
  },
  {
    name: 'Bronze Chain Greaves',
    usage: 'SENTRY',
    level: 4,
    bonus: 50,
    cost: 25000,
    race: 'ALL',
    type: 'BOOTS',
    armoryLevel: 4,
    quantity: 0,
    killingStrength: 20,
    defenseStrength: 30
  },
  {
    name: 'Padded Bracers',
    usage: 'SENTRY',
    level: 1,
    bonus: 3,
    cost: 1500,
    race: 'ALL',
    type: 'BRACERS',
    armoryLevel: 1,
    quantity: 0,
    killingStrength: 1,
    defenseStrength: 2
  },
  {
    name: 'Leather Bracers',
    usage: 'SENTRY',
    level: 2,
    bonus: 5,
    cost: 2500,
    race: 'ALL',
    type: 'BRACERS',
    armoryLevel: 2,
    quantity: 0,
    killingStrength: 2,
    defenseStrength: 3
  },
  {
    name: 'Studded Leather Bracers',
    usage: 'SENTRY',
    level: 3,
    bonus: 10,
    cost: 5000,
    race: 'ALL',
    type: 'BRACERS',
    armoryLevel: 3,
    quantity: 0,
    killingStrength: 5,
    defenseStrength: 5
  },
  {
    name: 'Bronze Chain Bracers',
    usage: 'SENTRY',
    level: 4,
    bonus: 20,
    cost: 10000,
    race: 'ALL',
    type: 'BRACERS',
    armoryLevel: 4,
    quantity: 0,
    killingStrength: 8,
    defenseStrength: 12
  },
  {
    name: 'Small Wooden Shield',
    usage: 'SENTRY',
    level: 1,
    bonus: 12,
    cost: 6000,
    race: 'ALL',
    type: 'SHIELD',
    armoryLevel: 1,
    quantity: 0,
    killingStrength: 2,
    defenseStrength: 10
  },
  {
    name: 'Medium Wooden Shield',
    usage: 'SENTRY',
    level: 2,
    bonus: 25,
    cost: 12500,
    race: 'ALL',
    type: 'SHIELD',
    armoryLevel: 2,
    quantity: 0,
    killingStrength: 5,
    defenseStrength: 20
  },
  {
    name: 'Large Wooden Shield',
    usage: 'SENTRY',
    level: 3,
    bonus: 50,
    cost: 25000,
    race: 'ALL',
    type: 'SHIELD',
    armoryLevel: 3,
    quantity: 0,
    killingStrength: 10,
    defenseStrength: 40
  },
  {
    name: 'Bronze Studded Shield',
    usage: 'SENTRY',
    level: 4,
    bonus: 100,
    cost: 50000,
    race: 'ALL',
    type: 'SHIELD',
    armoryLevel: 4,
    quantity: 0,
    killingStrength: 40,
    defenseStrength: 60
  },
  {
    name: 'Great Sword',
    usage: 'OFFENSE',
    level: 6,
    bonus: 1200,
    cost: 600000,
    type: 'WEAPON',
    race: 'HUMAN',
    armoryLevel: 5,
    quantity: 0,
    killingStrength: 960,
    defenseStrength: 240
  },
  {
    name: 'Elven Longbow',
    usage: 'OFFENSE',
    level: 6,
    bonus: 1200,
    cost: 600000,
    type: 'WEAPON',
    race: 'ELF',
    armoryLevel: 5,
    quantity: 0,
    killingStrength: 960,
    defenseStrength: 240
  }
];
