import type { Unit } from '@/types/typings';

export const UnitTypes: Unit[] = [
  {
    name: 'Citizen',
    type: 'CITIZEN',
    level: 1,
    bonus: 0,
    cost: 0,
    fortLevel: 1,
    hp: 10,
    killingStrength: 2,
    defenseStrength: 1,
  },
  {
    name: 'Worker',
    type: 'WORKER',
    level: 1,
    bonus: 65,
    cost: 2000,
    fortLevel: 1,
    hp: 20,
    killingStrength: 3,
    defenseStrength: 1,
  },
  {
    name: 'Soldier',
    type: 'OFFENSE',
    level: 1,
    bonus: 3,
    cost: 1500,
    fortLevel: 1,
    hp: 10,
    killingStrength: 5,
    defenseStrength: 2,
  },
  {
    name: 'Knight',
    type: 'OFFENSE',
    level: 2,
    bonus: 20,
    cost: 10000,
    fortLevel: 4,
    hp: 20,
    killingStrength: 15,
    defenseStrength: 5,
  },
  {
    name: 'Berserker',
    type: 'OFFENSE',
    level: 3,
    bonus: 50,
    cost: 25000,
    fortLevel: 7,
    hp: 30,
    killingStrength: 40,
    defenseStrength: 10,
  },
  {
    name: 'Guard',
    type: 'DEFENSE',
    level: 1,
    bonus: 3,
    cost: 1500,
    fortLevel: 1,
    hp: 10,
    killingStrength: 3,
    defenseStrength: 5,
  },
  {
    name: 'Archer',
    type: 'DEFENSE',
    level: 2,
    bonus: 20,
    cost: 10000,
    fortLevel: 4,
    hp: 20,
    killingStrength: 15,
    defenseStrength: 5,
  },
  {
    name: 'Royal Guard',
    type: 'DEFENSE',
    level: 3,
    bonus: 50,
    cost: 25000,
    fortLevel: 7,
    hp: 30,
    killingStrength: 40,
    defenseStrength: 10,
  },
  {
    name: 'Spy',
    type: 'SPY',
    level: 1,
    bonus: 3,
    cost: 1500,
    fortLevel: 1,
    hp: 10,
    killingStrength: 3,
    defenseStrength: 1,
  },
  {
    name: 'Infiltrator',
    type: 'SPY',
    level: 2,
    bonus: 20,
    cost: 10000,
    fortLevel: 8,
    hp: 20,
    killingStrength: 5,
    defenseStrength: 2,
  },
  {
    name: 'Assassin',
    type: 'SPY',
    level: 3,
    bonus: 50,
    cost: 25000,
    fortLevel: 12,
    hp: 30,
    killingStrength: 270,
    defenseStrength: 225,
  },
  {
    name: 'Sentry',
    type: 'SENTRY',
    level: 1,
    bonus: 3,
    cost: 1500,
    fortLevel: 1,
    hp: 10,
    killingStrength: 3,
    defenseStrength: 5,
  },
  {
    name: 'Sentinel',
    type: 'SENTRY',
    level: 2,
    bonus: 20,
    cost: 10000,
    fortLevel: 8,
    hp: 20,
    killingStrength: 15,
    defenseStrength: 20,
  },
  {
    name: 'Inquisitor',
    type: 'SENTRY',
    level: 3,
    bonus: 50,
    cost: 25000,
    fortLevel: 12,
    hp: 30,
    killingStrength: 225,
    defenseStrength: 250,
  },
];
