import type { Unit } from '@/types/typings';

export const UnitTypes: Unit[] = [
  {
    name: 'Citizen',
    type: 'CITIZEN',
    level: 1,
    bonus: 0,
    cost: 0,
    fortLevel: 1,
    hp: 10,
    MeleeAtkPower: 2,
    MeleeDefPower: 1,
    RangedAtkPower: 0,
    RangedDefPower: 0,
    closeCombatPercentage: 100,
    rangedPercentage: 0,
  },
  {
    name: 'Worker',
    type: 'WORKER',
    level: 1,
    bonus: 65,
    cost: 2000,
    fortLevel: 1,
    hp: 20,
    MeleeAtkPower: 3,
    MeleeDefPower: 1,
    RangedAtkPower: 0,
    RangedDefPower: 0,
    closeCombatPercentage: 100,
    rangedPercentage: 0,
  },
  {
    name: 'Soldier',
    type: 'OFFENSE',
    level: 1,
    bonus: 3,
    cost: 1500,
    fortLevel: 1,
    hp: 10,
    MeleeAtkPower: 5,
    MeleeDefPower: 2,
    RangedAtkPower: 0,
    RangedDefPower: 0,
    closeCombatPercentage: 100,
    rangedPercentage: 65,
  },
  {
    name: 'Knight',
    type: 'OFFENSE',
    level: 2,
    bonus: 20,
    cost: 10000,
    fortLevel: 4,
    hp: 20,
    MeleeAtkPower: 15,
    MeleeDefPower: 5,
    RangedAtkPower: 0,
    RangedDefPower: 0,
    closeCombatPercentage: 95,
    rangedPercentage: 45,
  },
  {
    name: 'Berserker',
    type: 'OFFENSE',
    level: 3,
    bonus: 50,
    cost: 25000,
    fortLevel: 7,
    hp: 30,
    MeleeAtkPower: 40,
    MeleeDefPower: 10,
    RangedAtkPower: 0,
    RangedDefPower: 0,
    closeCombatPercentage: 100,
    rangedPercentage: 10,
  },
  {
    name: 'Guard',
    type: 'DEFENSE',
    level: 1,
    bonus: 3,
    cost: 1500,
    fortLevel: 1,
    hp: 10,
    MeleeAtkPower: 3,
    MeleeDefPower: 5,
    RangedAtkPower: 0, // Defense units can have ranged, but this is a melee unit
    RangedDefPower: 0,
    closeCombatPercentage: 100,
    rangedPercentage: 0,
  },
  {
    name: 'Archer',
    type: 'DEFENSE',
    level: 2,
    bonus: 20,
    cost: 10000,
    fortLevel: 4,
    hp: 20,
    MeleeAtkPower: 5,
    MeleeDefPower: 5,
    RangedAtkPower: 15, // Archer has ranged attack
    RangedDefPower: 10,
    closeCombatPercentage: 75,
    rangedPercentage: 100,
  },
  {
    name: 'Royal Guard',
    type: 'DEFENSE',
    level: 3,
    bonus: 50,
    cost: 25000,
    fortLevel: 7,
    hp: 30,
    MeleeAtkPower: 40,
    MeleeDefPower: 10,
    RangedAtkPower: 0, // Royal Guard is a melee defense unit
    RangedDefPower: 0,
    closeCombatPercentage: 100,
    rangedPercentage: 10,
  },
  {
    name: 'Spy',
    type: 'SPY',
    level: 1,
    bonus: 3,
    cost: 1500,
    fortLevel: 1,
    hp: 10,
    MeleeAtkPower: 3,
    MeleeDefPower: 1,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    name: 'Infiltrator',
    type: 'SPY',
    level: 2,
    bonus: 20,
    cost: 10000,
    fortLevel: 8,
    hp: 20,
    MeleeAtkPower: 5,
    MeleeDefPower: 2,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    name: 'Assassin',
    type: 'SPY',
    level: 3,
    bonus: 50,
    cost: 25000,
    fortLevel: 12,
    hp: 30,
    MeleeAtkPower: 270,
    MeleeDefPower: 225,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    name: 'Sentry',
    type: 'SENTRY',
    level: 1,
    bonus: 3,
    cost: 1500,
    fortLevel: 1,
    hp: 10,
    MeleeAtkPower: 3,
    MeleeDefPower: 5,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    name: 'Sentinel',
    type: 'SENTRY',
    level: 2,
    bonus: 20,
    cost: 10000,
    fortLevel: 8,
    hp: 20,
    MeleeAtkPower: 15,
    MeleeDefPower: 20,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
  {
    name: 'Inquisitor',
    type: 'SENTRY',
    level: 3,
    bonus: 50,
    cost: 25000,
    fortLevel: 12,
    hp: 30,
    MeleeAtkPower: 225,
    MeleeDefPower: 250,
    RangedAtkPower: 0,
    RangedDefPower: 0,
  },
];
